name: Simple Test

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    name: Test Only
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: Run tests
        run: npm run test:run

      - name: Generate coverage
        run: npm run test:coverage

      - name: Display coverage summary
        run: |
          echo "## ✅ Tests Completed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All tests have passed and coverage reports have been generated." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### What was tested:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ ESLint code quality checks" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Prettier formatting verification" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Unit tests with Vitest" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Test coverage analysis" >> $GITHUB_STEP_SUMMARY
